#!/usr/bin/env python3
"""Extract the sugoroku board character-message dialogue pools from a PopnRhythmin
app binary and emit them either as a compiled-in C header (default, used by the CMake
configure step) or as a runtime binary asset.

The dialogue itself is copyrighted game content and is NOT shipped with this source.
Run this against your own copy of the app binary to regenerate the pools:

    # C header embedded at build time (what CMake does):
    python3 tools/extract_sugoroku_dialogue.py --format c   <binary> out.generated.inc
    # or a runtime .bin asset:
    python3 tools/extract_sugoroku_dialogue.py --format bin <binary> out.bin
    # empty tables, no binary needed (build fallback):
    python3 tools/extract_sugoroku_dialogue.py --emit-empty  out.generated.inc

C-header format: defines the six `static const char *const kCharGroup..[N]` tables that
TreasureMap.mm #includes. Binary format (little-endian): for each of the 6 pools in
order, an int32 entry-count then `count` records of {int32 byteLen, byteLen UTF-8 bytes}.

Pool pointer tables are absolute VA pointer arrays in the binary's __const; each entry
points at a NUL-terminated UTF-8 string in __cstring. Addresses are the Ghidra VAs at
image base 0x00004000.
"""
import argparse
import os
import struct
import sys

# (C table name, pointer-table VA, entry count) in the order getCharacterAssetName expects.
POOLS = [
    ("kCharGroup6Slot0", 0x1335c8, 41),
    ("kCharGroup6Slot1", 0x13366c, 35),
    ("kCharGroup6Slot2", 0x1336f8, 47),  # wac
    ("kCharGroup8Slot0", 0x1337b4, 64),
    ("kCharGroup8Slot1", 0x1338b4, 72),  # TOMOSUKE
    ("kCharGroup8Slot2", 0x1339d4, 71),
]

CPU_TYPE_ARM = 12
MH_MAGIC, MH_CIGAM = 0xFEEDFACE, 0xCEFAEDFE
FAT_MAGIC, FAT_CIGAM = 0xCAFEBABE, 0xBEBAFECA
LC_SEGMENT = 0x1


def u32le(b, o):
    return struct.unpack_from("<I", b, o)[0]


def select_thin(data):
    """Return the bytes of a 32-bit Mach-O image, unwrapping a fat binary."""
    if struct.unpack_from(">I", data, 0)[0] in (FAT_MAGIC, FAT_CIGAM):
        nfat = struct.unpack_from(">I", data, 4)[0]
        off, chosen = 8, None
        for _ in range(nfat):
            cputype, _sub, foff, fsize, _al = struct.unpack_from(">iIIII", data, off)
            off += 20
            if cputype == CPU_TYPE_ARM:
                chosen = (foff, fsize)
        if chosen is None:
            sys.exit("error: no 32-bit ARM slice in fat binary")
        return data[chosen[0]:chosen[0] + chosen[1]]
    return data


def parse_segments(image):
    if u32le(image, 0) not in (MH_MAGIC, MH_CIGAM):
        sys.exit("error: not a 32-bit Mach-O (magic 0x%08x)" % u32le(image, 0))
    ncmds = u32le(image, 16)
    off, segs = 28, []
    for _ in range(ncmds):
        cmd, cmdsize = struct.unpack_from("<II", image, off)
        if cmd == LC_SEGMENT:
            segs.append(struct.unpack_from("<IIII", image, off + 24))  # vmaddr,vmsize,fileoff,filesize
        if cmdsize == 0:
            break
        off += cmdsize
    return segs


def va_to_off(segs, va):
    for vmaddr, vmsize, fileoff, filesize in segs:
        if vmaddr <= va < vmaddr + vmsize:
            delta = va - vmaddr
            return fileoff + delta if delta < filesize else None
        # continue
    return None


def read_cstr(image, off):
    return image[off:image.index(b"\x00", off)]


def extract(binpath):
    """Return [(name, count, [bytes,...]), ...] for the six pools."""
    with open(binpath, "rb") as fh:
        image = select_thin(fh.read())
    segs = parse_segments(image)
    result = []
    for name, va, count in POOLS:
        toff = va_to_off(segs, va)
        if toff is None:
            sys.exit("error: pointer table VA 0x%x not in any segment" % va)
        strings = []
        for i in range(count):
            ptr = u32le(image, toff + i * 4)
            soff = va_to_off(segs, ptr)
            if soff is None:
                sys.exit("error: pool 0x%x entry %d -> VA 0x%x not in file" % (va, i, ptr))
            strings.append(read_cstr(image, soff))
        result.append((name, count, strings))
    return result


def c_literal(bs):
    """C string literal with safe escaping (3-digit octal for non-printables/high bytes)."""
    out = ['"']
    for byte in bs:
        if byte == 0x22:
            out.append('\\"')
        elif byte == 0x5C:
            out.append("\\\\")
        elif byte == 0x3F:            # escape '?' to avoid trigraphs
            out.append("\\?")
        elif 0x20 <= byte <= 0x7E:
            out.append(chr(byte))
        else:
            out.append("\\%03o" % byte)
    out.append('"')
    return "".join(out)


def write_c(outpath, pools):
    lines = [
        "// AUTO-GENERATED by tools/extract_sugoroku_dialogue.py -- do not edit or commit.",
        "// Sugoroku board character-message pools. Generated at CMake configure time from",
        "// an owned copy of the app binary; #included by TreasureMap.mm. If no binary was",
        "// supplied the tables are empty and getCharacterAssetName returns nullptr.",
        "",
    ]
    for name, count, strings in pools:
        if strings and any(len(s) for s in strings):
            lines.append("static const char *const %s[%d] = {" % (name, count))
            for s in strings:
                lines.append("    " + c_literal(s) + ",")
            lines.append("};")
        else:
            lines.append("static const char *const %s[%d] = {0};" % (name, count))
        lines.append("")
    with open(outpath, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))


def write_empty_c(outpath):
    write_c(outpath, [(name, count, []) for name, _va, count in POOLS])


def write_bin(outpath, pools):
    out = bytearray()
    for _name, count, strings in pools:
        out += struct.pack("<i", count)
        for s in strings:
            out += struct.pack("<i", len(s)) + s
    with open(outpath, "wb") as fh:
        fh.write(out)


def main():
    ap = argparse.ArgumentParser(description="Extract sugoroku dialogue pools.")
    ap.add_argument("binary", nargs="?", help="path to an owned PopnRhythmin app binary")
    ap.add_argument("out", help="output file")
    ap.add_argument("--format", choices=("c", "bin"), default="c",
                    help="c = compiled-in header (default); bin = runtime asset")
    ap.add_argument("--emit-empty", action="store_true",
                    help="write empty C tables without a binary (build fallback)")
    args = ap.parse_args()

    if args.emit_empty:
        write_empty_c(args.out)
        print("wrote empty sugoroku tables -> %s" % os.path.abspath(args.out))
        return

    if not args.binary:
        ap.error("a binary is required unless --emit-empty is given")
    pools = extract(args.binary)
    total_strings = sum(c for _n, c, _s in pools)
    total_bytes = sum(len(s) for _n, _c, ss in pools for s in ss)
    if args.format == "c":
        write_c(args.out, pools)
    else:
        write_bin(args.out, pools)
    print("extracted %d strings, %d content bytes -> %s (%s)"
          % (total_strings, total_bytes, os.path.abspath(args.out), args.format))


if __name__ == "__main__":
    main()
